services:
    armd_cms.main_menu.twig_extension:
        class: Armd\MainMenuBundle\Twig\Extension\MenuTwigExtension
        tags:
            -  { name: twig.extension }
        calls:
            - [ setContainer, [ @service_container ] ]