parameters:
    sip.resourse.setting.admin.class: SIP\ResourceBundle\Admin\SettingAdmin
    sip.resourse.setting.model.class: SIP\ResourceBundle\Entity\Setting

    sip.resourse.page.admin.class: SIP\ResourceBundle\Admin\PageAdmin
    sip.resourse.page.model.class: SIP\ResourceBundle\Entity\Page

    sonata.media.admin.media.class: SIP\ResourceBundle\Admin\MediaAdmin
    sonata.user.admin.user.class: SIP\ResourceBundle\Admin\UserAdmin

    sip.resourse.metadata.admin.class: SIP\ResourceBundle\Admin\MetaDataAdmin
    sip.resourse.metadata.model.class: SIP\ResourceBundle\Entity\MetaData
services:
    sip.resourse.setting.admin:
        class: %sip.resourse.setting.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Setting }
        arguments: [null, %sip.resourse.setting.model.class%, null, @service_container]

    sip.resourse.page.admin:
        class: %sip.resourse.page.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Page }
        arguments: [null, %sip.resourse.page.model.class%, null]

    sonata.user.admin.user:
        class: %sonata.user.admin.user.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: %sonata.user.admin.groupname%, label: users, label_catalogue: "SonataUserBundle", label_translator_strategy: "sonata.admin.label.strategy.underscore" }
        arguments: [null, %sonata.user.admin.user.entity%, %sonata.user.admin.user.controller%, @service_container]
        calls:
            - [setTranslationDomain, [ %sonata.user.admin.user.translation_domain% ] ]
            - [setUserManager, [ @fos_user.user_manager ] ]

    sonata.media.admin.gallery:
        class: %sonata.media.admin.gallery.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: sonata_media, label: gallery, show_in_dashboard: false }
        arguments: [null, %sonata.media.admin.gallery.entity%, %sonata.media.admin.gallery.controller%, @sonata.media.pool]
        calls:
            - [setTranslationDomain, [ %sonata.media.admin.gallery.translation_domain% ] ]
            - [setTemplates, [ {list: SonataMediaBundle:GalleryAdmin:list.html.twig} ] ]

    sip.resourse.metadata.admin:
        class: %sip.resourse.metadata.admin.class%
        tags:
            - { name: sonata.admin, manager_type: orm, group: content, label: Metadata }
        arguments: [null, %sip.resourse.metadata.model.class%, null]