services:
    sip.image_file.form.type:
        class: SIP\ResourceBundle\Form\Type\ImageFileType
        tags:
            - { name: form.type, alias: image_file_type }

    sonata.user.serializer.handler.user:
        class: Sonata\UserBundle\Serializer\UserSerializerHandler
        tags:
            - { name: jms_serializer.subscribing_handler }
        arguments:
            - [ sonata.user.mongodb.user_manager ]