parameters:

services:
    sip_resource.helper.settings:
        class: SIP\ResourceBundle\Helper\SettingsHelper
        arguments: ['@service_container']

    sip_resource.twig.settings:
        class: SIP\ResourceBundle\Twig\Extension\SettingsExtension
        arguments: ['@service_container']
        tags: [{ name: twig.extension }]

    meta.twig_extension:
        class: SIP\ResourceBundle\Twig\Extension\MetaExtension
        arguments:
              doctrine: "@doctrine"
        public: false
        tags:
            - { name: twig.extension }

    sip.resource.form.show.image.type:
        class: SIP\ResourceBundle\Form\Type\ShowImageType
        tags:
            - { name: form.type, alias: show_sonata_image }

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }