parameters:
    armd_cms.response_listener.class:        Armd\Bundle\CmsBundle\Listener\ResponseListener
    armd_cms.page_url_update_listener.class: Armd\Bundle\CmsBundle\Listener\PageUrlUpdateListener

services:
    armd_cms.response_listener:
        class: %armd_cms.response_listener.class%
        tags:
            - { name: kernel.event_listener, event: kernel.response, method: onCoreResponse }
        arguments: [@router, @armd_cms.page_manager, %armd_cms.ignore_route_patterns%]

    armd_cms.page_url_update_listener:
        class: %armd_cms.page_url_update_listener.class%
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postRemove }
        arguments: [@service_container]