services:
    armd.content.statistic.admin:
        class: Armd\Bundle\AdminBundle\Admin\StatisticAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: module, label: Statistic }
            - { name: armd.content.admin }
        arguments: [null, Armd\Bundle\AdminBundle\Entity\Statistic, ArmdCmsBundle:BaseResponse, @service_container]
    
    armd_admin.twig.extension:
        class: Armd\Bundle\AdminBundle\Twig\Extension\ArmdAdminExtension
        tags:
            - { name: twig.extension }
        arguments: [@service_container]

    sonata.admin.builder.orm_form:
        class: Armd\Bundle\AdminBundle\Builder\FormContractor
        arguments: [@form.factory]

    sonata.block.service.action:
        class: Armd\Bundle\AdminBundle\Block\ActionBlockService
        tags:
            - { name: sonata.block}
        arguments: [sonata.block.action, @service_container]

    sonata.admin.form.type.model_choice:
        class: Armd\Bundle\AdminBundle\Form\ModelType
        tags:
            - { name: form.type, alias: sonata_type_model }

    sonata.admin.controller.admin:
        class: Armd\Bundle\AdminBundle\Controller\HelperController
        arguments: [@twig, @sonata.admin.pool, @sonata.admin.helper]
