parameters:
    armd_news.controller.news.class: Armd\NewsBundle\Controller\NewsController

services:
    armd_news.controller.news:
        class: %armd_news.controller.news.class%
        calls:
            - [ setContainer, [ @service_container ] ]