sonata_admin:
    title:      SIP Admin Panel
    title_logo: bundles/sipresource/img/logo_litle.png
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
    templates:
        edit:   SIPResourceBundle:Admin:edit.html.twig
        layout: SIPResourceBundle:Admin:standard_layout.html.twig
        list:   SIPResourceBundle:Admin:list.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.user.block.menu:
        sonata.user.block.account:
        sonata.admin.block.search_result:
            contexts: [admin]
