sonata_user:
    security_acl: false
    manager_type: mongodb
    impersonating_route: sonata_user_impersonating
    class:
        user:   SIP\ResourceBundle\Document\User
        group:  SIP\ResourceBundle\Document\Group
    profile:  # Profile Form (firstname, lastname, etc ...)
        form:
            type:               sonata_user_profile
            handler:            sonata.user.profile.form.handler.default
            name:               sonata_user_profile_form
            validation_groups:  [Profile]

fos_user:
    db_driver:      mongodb
    firewall_name:  main
    user_class:     SIP\ResourceBundle\Document\User

    group:
        group_class: SIP\ResourceBundle\Document\Group

    profile:  # Authentication Form
        form:
            type:               fos_user_profile
            name:               fos_user_profile_form
            validation_groups:  [Authentication] # Please note : this is not the default value